add_library(smesh_model
  src/AccScaleUnit.cpp
  src/memory/Accum.cpp
  src/ArbComplete.cpp
  src/memory/ArbReadLocal.cpp
  src/memory/ArbWriteLocal.cpp
  src/dma/DmaIssueQueues.cpp
  src/dma/DmaReadCompletionMux.cpp
  src/dma/DmaReader.cpp
  src/dma/DmaWriter.cpp
  src/controllers/ex/ExCtrl.cpp
  src/controllers/ex/ExCtrlCompletion.cpp
  src/controllers/ex/ExCtrlDecoder.cpp
  src/controllers/ex/ExCtrlFeedSignals.cpp
  src/controllers/ex/ExCtrlMeshCntlPack.cpp
  src/controllers/ex/ExCtrlMeshCntlDeqCtrl.cpp
  src/controllers/ex/ExCtrlMeshCntlQueue.cpp
  src/controllers/ex/ExCtrlMeshInSelPad.cpp
  src/controllers/ex/ExCtrlMeshTagSelect.cpp
  src/controllers/ex/ExCtrlOperandPack.cpp
  src/controllers/ex/ExCtrlQueues.cpp
  src/controllers/ex/ExCtrlReadPriority.cpp
  src/controllers/ex/ExCtrlReadReqLogic.cpp
  src/controllers/ex/ExCtrlRowFeedState.cpp
  src/controllers/ex/ExCtrlRowAddr.cpp
  src/controllers/ex/ExCtrlRowPad.cpp
  src/controllers/ex/ExCtrlState.cpp
  src/controllers/ex/ExCtrlState2.cpp
  src/controllers/ex/ExCtrlWriteback.cpp
  src/controllers/ld/LdCtrl.cpp
  src/controllers/ld/LdCtrlCmdDec.cpp
  src/controllers/ld/LdCtrlCmdTracker.cpp
  src/controllers/ld/LdCtrlDmaReq.cpp
  src/controllers/ld/LdCtrlGeom.cpp
  src/controllers/ld/LdCtrlQueues.cpp
  src/controllers/ld/LdCtrlState.cpp
  src/mvin/MvinLocalRouter.cpp
  src/mvin/MvinPixelRepeater.cpp
  src/mvin/MvinScale.cpp
  src/mesh/MeshCore.cpp
  src/mesh/MeshHull.cpp
  src/mesh/Mesher.cpp
  src/Normalizer.cpp
  src/SmeshCmdQueues.cpp
  src/legacy/SmeshDevice.cpp
  src/SmeshRS.cpp
  src/Smesh.cpp
  src/memory/Spad.cpp
  src/memory/SpadReadPipes.cpp
  src/memory/SpadWriter.cpp
  src/controllers/st/StCtrl.cpp
  src/controllers/st/StCtrlCmdDec.cpp
  src/controllers/st/StCtrlCmdTracker.cpp
  src/controllers/st/StCtrlDmaReq.cpp
  src/controllers/st/StCtrlGeom.cpp
  src/controllers/st/StCtrlQueues.cpp
  src/controllers/st/StCtrlState.cpp
  src/mvout/StIssueCtrl.cpp
  src/mvout/StIssueMux.cpp
  src/mvout/StNormCtrl.cpp
  src/mvout/StReadCtrl.cpp
  src/mvout/StScaleCtrl.cpp
  src/mvin/WriteCtrl.cpp
)

target_include_directories(smesh_model
  PUBLIC
    include
    include/common
    include/legacy
    include/memory
    include/controllers/ex
    include/controllers/ld
    include/controllers/st
    include/mesh
    include/mvin
    include/mvout
    include/dma
    ${CMAKE_CURRENT_SOURCE_DIR}/../smem/include
)

target_link_libraries(smesh_model
  PUBLIC
    cascade
)

add_executable(tb_ex_ctrl_arch
  src/tb_ex_ctrl_arch.cpp
)

target_link_libraries(tb_ex_ctrl_arch
  PRIVATE
    smesh_model
    cascade
    -lz
    -ltermcap
    -lpthread
)

add_executable(tb_rs_ld_issue
  src/tb_rs_ld_issue.cpp
)

target_link_libraries(tb_rs_ld_issue
  PRIVATE
    smesh_model
    smem_memory
    cascade
    -lz
    -ltermcap
    -lpthread
)

add_executable(tb_smesh_top_acc_full_load
  src/tb_smesh_top_acc_full_load.cpp
)

target_link_libraries(tb_smesh_top_acc_full_load
  PRIVATE
    smesh_model
    cascade
    -lz
    -ltermcap
    -lpthread
)

if(BUILD_TESTING)
  add_subdirectory(tests)
endif()
